---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-export-from-clone
spec:
  dataSource:
    name: csi-pvc
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-export-csi
