apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-export-csi
provisioner: nfs-export.csi.k8s.io
parameters:
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
  backendStorageClass: csi-hostpath-sc
  backendPodImage: daocloud.io/piraeus/nfs-ganesha:latest
  hostIPs: 10.211.55.0/24
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1